#############################################################################
# Makefile for building: MainWindow
# Generated by qmake (2.01a) (Qt 4.8.4) on: Fri Mar 1 00:18:57 2013
# Project:  MainWindow.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile MainWindow.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Iclasses/mainwindow -Idialogs/sort -Idialogs/gotocell -Idialogs/finddialog -Iclasses/spreadsheet -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		classes/mainwindow/mainwindow.cpp \
		classes/mainwindow/mainwindow_private.cpp \
		classes/mainwindow/mainwindow_protected.cpp \
		classes/mainwindow/mainwindow_slots.cpp \
		classes/spreadsheet/spreadsheet_constructor.cpp \
		classes/spreadsheet/spreadsheet_private.cpp \
		classes/spreadsheet/spreadsheet_public.cpp \
		classes/spreadsheet/spreadsheet_slots.cpp \
		dialogs/finddialog/finddialog.cpp \
		dialogs/gotocell/gotocelldialog.cpp \
		dialogs/sort/sortdialog.cpp \
		classes/cell/cell.cpp moc_mainwindow.cpp \
		moc_spreadsheet.cpp \
		moc_finddialog.cpp \
		moc_gotocelldialog.cpp \
		moc_sortdialog.cpp \
		qrc_SPREADSHEET_RECOURCES.cpp
OBJECTS       = main.o \
		mainwindow.o \
		mainwindow_private.o \
		mainwindow_protected.o \
		mainwindow_slots.o \
		spreadsheet_constructor.o \
		spreadsheet_private.o \
		spreadsheet_public.o \
		spreadsheet_slots.o \
		finddialog.o \
		gotocelldialog.o \
		sortdialog.o \
		cell.o \
		moc_mainwindow.o \
		moc_spreadsheet.o \
		moc_finddialog.o \
		moc_gotocelldialog.o \
		moc_sortdialog.o \
		qrc_SPREADSHEET_RECOURCES.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		MainWindow.pro
QMAKE_TARGET  = MainWindow
DESTDIR       = 
TARGET        = MainWindow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_finddialog.h ui_gotocelldialog.h ui_sortdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MainWindow.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile MainWindow.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile MainWindow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MainWindow1.0.0 || $(MKDIR) .tmp/MainWindow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents classes/mainwindow/mainwindow.h classes/spreadsheet/spreadsheet.h dialogs/finddialog/finddialog.h dialogs/gotocell/gotocelldialog.h dialogs/sort/sortdialog.h classes/cell/cell.h .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents SPREADSHEET_RECOURCES.qrc .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents main.cpp classes/mainwindow/mainwindow.cpp classes/mainwindow/mainwindow_private.cpp classes/mainwindow/mainwindow_protected.cpp classes/mainwindow/mainwindow_slots.cpp classes/spreadsheet/spreadsheet_constructor.cpp classes/spreadsheet/spreadsheet_private.cpp classes/spreadsheet/spreadsheet_public.cpp classes/spreadsheet/spreadsheet_slots.cpp dialogs/finddialog/finddialog.cpp dialogs/gotocell/gotocelldialog.cpp dialogs/sort/sortdialog.cpp classes/cell/cell.cpp .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents dialogs/finddialog/finddialog.ui dialogs/gotocell/gotocelldialog.ui dialogs/sort/sortdialog.ui .tmp/MainWindow1.0.0/ && (cd `dirname .tmp/MainWindow1.0.0` && $(TAR) MainWindow1.0.0.tar MainWindow1.0.0 && $(COMPRESS) MainWindow1.0.0.tar) && $(MOVE) `dirname .tmp/MainWindow1.0.0`/MainWindow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MainWindow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_spreadsheet.cpp moc_finddialog.cpp moc_gotocelldialog.cpp moc_sortdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_spreadsheet.cpp moc_finddialog.cpp moc_gotocelldialog.cpp moc_sortdialog.cpp
moc_mainwindow.cpp: classes/mainwindow/mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) classes/mainwindow/mainwindow.h -o moc_mainwindow.cpp

moc_spreadsheet.cpp: classes/cell/cell.h \
		classes/spreadsheet/spreadsheet.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) classes/spreadsheet/spreadsheet.h -o moc_spreadsheet.cpp

moc_finddialog.cpp: dialogs/finddialog/ui_finddialog.h \
		dialogs/finddialog/finddialog.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) dialogs/finddialog/finddialog.h -o moc_finddialog.cpp

moc_gotocelldialog.cpp: dialogs/gotocell/ui_gotocelldialog.h \
		dialogs/gotocell/gotocelldialog.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) dialogs/gotocell/gotocelldialog.h -o moc_gotocelldialog.cpp

moc_sortdialog.cpp: dialogs/sort/ui_sortdialog.h \
		dialogs/sort/sortdialog.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) dialogs/sort/sortdialog.h -o moc_sortdialog.cpp

compiler_rcc_make_all: qrc_SPREADSHEET_RECOURCES.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_SPREADSHEET_RECOURCES.cpp
qrc_SPREADSHEET_RECOURCES.cpp: SPREADSHEET_RECOURCES.qrc \
		images/splash.png \
		images/my_spreadsheet_icon.png \
		images/my_spreadsheet_icon_alt.png
	/usr/lib64/qt4/bin/rcc -name SPREADSHEET_RECOURCES SPREADSHEET_RECOURCES.qrc -o qrc_SPREADSHEET_RECOURCES.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_finddialog.h ui_gotocelldialog.h ui_sortdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_finddialog.h ui_gotocelldialog.h ui_sortdialog.h
ui_finddialog.h: dialogs/finddialog/finddialog.ui
	/usr/lib64/qt4/bin/uic dialogs/finddialog/finddialog.ui -o ui_finddialog.h

ui_gotocelldialog.h: dialogs/gotocell/gotocelldialog.ui
	/usr/lib64/qt4/bin/uic dialogs/gotocell/gotocelldialog.ui -o ui_gotocelldialog.h

ui_sortdialog.h: dialogs/sort/sortdialog.ui
	/usr/lib64/qt4/bin/uic dialogs/sort/sortdialog.ui -o ui_sortdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp classes/mainwindow/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: classes/mainwindow/mainwindow.cpp classes/mainwindow/mainwindow.h \
		dialogs/sort/sortdialog.h \
		dialogs/sort/ui_sortdialog.h \
		dialogs/gotocell/gotocelldialog.h \
		dialogs/gotocell/ui_gotocelldialog.h \
		dialogs/finddialog/finddialog.h \
		dialogs/finddialog/ui_finddialog.h \
		classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o classes/mainwindow/mainwindow.cpp

mainwindow_private.o: classes/mainwindow/mainwindow_private.cpp classes/mainwindow/mainwindow.h \
		dialogs/sort/sortdialog.h \
		dialogs/sort/ui_sortdialog.h \
		dialogs/gotocell/gotocelldialog.h \
		dialogs/gotocell/ui_gotocelldialog.h \
		dialogs/finddialog/finddialog.h \
		dialogs/finddialog/ui_finddialog.h \
		classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow_private.o classes/mainwindow/mainwindow_private.cpp

mainwindow_protected.o: classes/mainwindow/mainwindow_protected.cpp classes/mainwindow/mainwindow.h \
		dialogs/sort/sortdialog.h \
		dialogs/sort/ui_sortdialog.h \
		dialogs/gotocell/gotocelldialog.h \
		dialogs/gotocell/ui_gotocelldialog.h \
		dialogs/finddialog/finddialog.h \
		dialogs/finddialog/ui_finddialog.h \
		classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow_protected.o classes/mainwindow/mainwindow_protected.cpp

mainwindow_slots.o: classes/mainwindow/mainwindow_slots.cpp classes/mainwindow/mainwindow.h \
		dialogs/sort/sortdialog.h \
		dialogs/sort/ui_sortdialog.h \
		dialogs/gotocell/gotocelldialog.h \
		dialogs/gotocell/ui_gotocelldialog.h \
		dialogs/finddialog/finddialog.h \
		dialogs/finddialog/ui_finddialog.h \
		classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow_slots.o classes/mainwindow/mainwindow_slots.cpp

spreadsheet_constructor.o: classes/spreadsheet/spreadsheet_constructor.cpp classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spreadsheet_constructor.o classes/spreadsheet/spreadsheet_constructor.cpp

spreadsheet_private.o: classes/spreadsheet/spreadsheet_private.cpp classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spreadsheet_private.o classes/spreadsheet/spreadsheet_private.cpp

spreadsheet_public.o: classes/spreadsheet/spreadsheet_public.cpp classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spreadsheet_public.o classes/spreadsheet/spreadsheet_public.cpp

spreadsheet_slots.o: classes/spreadsheet/spreadsheet_slots.cpp classes/spreadsheet/spreadsheet.h \
		classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spreadsheet_slots.o classes/spreadsheet/spreadsheet_slots.cpp

finddialog.o: dialogs/finddialog/finddialog.cpp dialogs/finddialog/finddialog.h \
		dialogs/finddialog/ui_finddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finddialog.o dialogs/finddialog/finddialog.cpp

gotocelldialog.o: dialogs/gotocell/gotocelldialog.cpp dialogs/gotocell/gotocelldialog.h \
		dialogs/gotocell/ui_gotocelldialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gotocelldialog.o dialogs/gotocell/gotocelldialog.cpp

sortdialog.o: dialogs/sort/sortdialog.cpp dialogs/sort/sortdialog.h \
		dialogs/sort/ui_sortdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sortdialog.o dialogs/sort/sortdialog.cpp

cell.o: classes/cell/cell.cpp classes/cell/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o classes/cell/cell.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_spreadsheet.o: moc_spreadsheet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spreadsheet.o moc_spreadsheet.cpp

moc_finddialog.o: moc_finddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finddialog.o moc_finddialog.cpp

moc_gotocelldialog.o: moc_gotocelldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gotocelldialog.o moc_gotocelldialog.cpp

moc_sortdialog.o: moc_sortdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sortdialog.o moc_sortdialog.cpp

qrc_SPREADSHEET_RECOURCES.o: qrc_SPREADSHEET_RECOURCES.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_SPREADSHEET_RECOURCES.o qrc_SPREADSHEET_RECOURCES.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

